symfony/grafikart3/src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 * @UniqueEntity("title")
 * @Vich\Uploadable
 */
class Property
{
  /**
   * On définit une constante
   * Ici le type de chauffage
   * Si 0 -> chauffage électrique
   * Si 1 -> chauffage au gaz
   */
  const HEAT = [
    0 => 'Electrique',
    1 => 'Gaz',
  ];
  /**
   * @ORM\Id()
   * @ORM\GeneratedValue()
   * @ORM\Column(type="integer")
   */
  private $id;

  /**
   * @ORM\Column(type="string", length=255)
   *
   * @var string|null
   */
  private $filename;

  /**
   * NOTE: This is not a mapped field of entity metadata, just a simple property.
   * 
   * @Assert\Image(
   *   mimeTypes="image/jpeg"
   * )
   * @Vich\UploadableField(mapping="property_image", fileNameProperty="filename")
   * 
   * @var File|null
   */
  private $imageFile;

  /**
   * @ORM\Column(type="string", length=255)
   * @Assert\Length(min=5, max=255)
   */
  private $title;

  /**
   * @ORM\Column(type="text", nullable=true)
   */
  private $description;

  /**
   * @ORM\Column(type="integer")
   * @Assert\Range(min=10, max=400)
   */
  private $surface;

  /**
   * @ORM\Column(type="integer")
   */
  private $rooms;

  /**
   * @ORM\Column(type="integer")
   */
  private $bedrooms;

  /**
   * @ORM\Column(type="integer")
   */
  private $floor;

  /**
   * @ORM\Column(type="integer")
   */
  private $price;

  /**
   * @ORM\Column(type="integer")
   */
  private $heat;

  /**
   * @ORM\Column(type="string", length=255)
   */
  private $city;

  /**
   * @ORM\Column(type="string", length=255)
   */
  private $address;

  /**
   * @ORM\Column(type="string", length=255)
   * @Assert\Regex("/^[0-9]{5}$/")
   */
  private $zipcode;

  /**
   * @ORM\Column(type="boolean", options={"default": false})
   */
  private $sold = false;

  /**
   * @ORM\Column(type="datetime")
   */
  private $createdAt;

  /**
   * @ORM\ManyToMany(targetEntity=Option::class, inversedBy="properties")
   */
  private $options;

  /**
   * @ORM\Column(type="datetime")
   */
  private $updatedAt;

  public function __construct()
  {
    $this->createdAt = new \DateTime;
    $this->options = new ArrayCollection();
  }

  public function getId(): ?int
  {
    return $this->id;
  }

  public function getTitle(): ?string
  {
    return $this->title;
  }

  public function setTitle(string $title): self
  {
    $this->title = $title;

    return $this;
  }

  public function getSlug(): string
  {
    return (new Slugify)->slugify($this->title);
  }

  public function getDescription(): ?string
  {
    return $this->description;
  }

  public function setDescription(?string $description): self
  {
    $this->description = $description;

    return $this;
  }

  public function getSurface(): ?int
  {
    return $this->surface;
  }

  public function setSurface(int $surface): self
  {
    $this->surface = $surface;

    return $this;
  }

  public function getRooms(): ?int
  {
    return $this->rooms;
  }

  public function setRooms(int $rooms): self
  {
    $this->rooms = $rooms;

    return $this;
  }

  public function getBedrooms(): ?int
  {
    return $this->bedrooms;
  }

  public function setBedrooms(int $bedrooms): self
  {
    $this->bedrooms = $bedrooms;

    return $this;
  }

  public function getFloor(): ?int
  {
    return $this->floor;
  }

  public function setFloor(int $floor): self
  {
    $this->floor = $floor;

    return $this;
  }

  public function getPrice(): ?int
  {
    return $this->price;
  }

  public function setPrice(int $price): self
  {
    $this->price = $price;

    return $this;
  }

  public function getFormattedPrice()
  {
    return number_format($this->price, 0, '', ' ');
  }

  public function getHeat(): ?int
  {
    return $this->heat;
  }

  public function setHeat(int $heat): self
  {
    $this->heat = $heat;

    return $this;
  }

  public function getHeatType(): string
  {
    return self::HEAT[$this->heat];
  }

  public function getCity(): ?string
  {
    return $this->city;
  }

  public function setCity(string $city): self
  {
    $this->city = $city;

    return $this;
  }

  public function getAddress(): ?string
  {
    return $this->address;
  }

  public function setAddress(string $address): self
  {
    $this->address = $address;

    return $this;
  }

  public function getZipcode(): ?string
  {
    return $this->zipcode;
  }

  public function setZipcode(string $zipcode): self
  {
    $this->zipcode = $zipcode;

    return $this;
  }

  public function getSold(): ?bool
  {
    return $this->sold;
  }

  public function setSold(bool $sold): self
  {
    $this->sold = $sold;

    return $this;
  }

  public function getCreatedAt(): ?\DateTimeInterface
  {
    return $this->createdAt;
  }

  public function setCreatedAt(\DateTimeInterface $createdAt): self
  {
    $this->createdAt = $createdAt;

    return $this;
  }

  /**
   * @return Collection|Option[]
   */
  public function getOptions(): Collection
  {
    return $this->options;
  }

  public function addOption(Option $option): self
  {
    if (!$this->options->contains($option)) {
      $this->options[] = $option;
      $option->addProperty($this);
    }

    return $this;
  }

  public function removeOption(Option $option): self
  {
    if ($this->options->contains($option)) {
      $this->options->removeElement($option);
      $option->removeProperty($this);
    }

    return $this;
  }

  /**
   * Get the value of filename
   *
   * @return  string|null
   */
  public function getFilename(): ?string
  {
    return $this->filename;
  }

  /**
   * Set the value of filename
   * @param  string|null  $filename
   * @return  Property
   */
  public function setFilename(?string $filename): Property
  {
    $this->filename = $filename;
    return $this;
  }

  /**
   * Get nOTE: This is not a mapped field of entity metadata, just a simple property.
   * @return  File|null
   */
  public function getImageFile(): ?File
  {
    return $this->imageFile;
  }

  /**
   * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
   * of 'UploadedFile' is injected into this setter to trigger the update. If this
   * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
   * must be able to accept an instance of 'File' as the bundle will inject one here
   * during Doctrine hydration.
   * 
   * Set nOTE: This is not a mapped field of entity metadata, just a simple property.
   *
   * @param File|null|\Symfony\Component\HttpFoundation\File\UploadedFile $imageFile NOTE: This is not a mapped field of entity metadata, just a simple property.
   * @return  Property
   */
  public function setImageFile($imageFile): Property
  {
    $this->imageFile = $imageFile;

    // Only change the updated af if the file is really uploaded to avoid database updates.
    // This is needed when the file should be set when loading the entity.
    if ($this->imageFile instanceof UploadedFile) {
      $this->updatedAt = new \DateTime('now');
    }

    return $this;
  }

  public function getUpdatedAt(): ?\DateTimeInterface
  {
    return $this->updatedAt;
  }

  public function setUpdatedAt(\DateTimeInterface $updatedAt): self
  {
    $this->updatedAt = $updatedAt;

    return $this;
  }
}

symfony/grafikart3/src/Controller/AgencyController.php
<?php

namespace App\Controller;

use App\Entity\Contact;
use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Form\ContactType;
use App\Form\PropertySearchType;
use App\Notification\ContactNotification;
use App\Repository\PropertyRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AgencyController extends AbstractController
{
	// /**
	//  * @Route("/agency", name="agency")
	//  */
	// public function index()
	// {
	// 	return $this->render('agency/index.html.twig', [
	// 		'controller_name' => 'AgencyController',
	// 	]);
	// }

	/**
	 * @Route("/", name="home")
	 */
	public function home(PropertyRepository $repository): Response
	{
		$properties = $repository->findLatest();

		return $this->render('agency/home.html.twig', [
			'properties' => $properties,
		]);
	}

	/**
	 * @Route("/add", name="agency_create")
	 */
	public function create(): Response
	{
		return $this->render('agency/create.html.twig', [
			'current_page' => 'properties',
			// 'current_page' => 'create_properties',
		]);
	}

	/**
	 * @Route("/biens", name="agency_properties")
	 */
	public function properties(PaginatorInterface $paginator, EntityManagerInterface $manager, Request $request, PropertyRepository $repository): Response
	{
		// $property = new Property;
		// $property->setTitle('Mon premier bien')
		// 	->setPrice(200000)
		// 	->setRooms(4)
		// 	->setBedrooms(3)
		// 	->setDescription('Description ici')
		// 	->setSurface(60)
		// 	->setFloor(4)
		// 	->setHeat(1)
		// 	->setCity('Montpellier')
		// 	->setAddress('15 Boulevard Gambetta')
		// 	->setZipcode('34000');

		// // $manager->persist($property);
		// // $manager->flush();
		// dump($property);

		/**
		 * Création du formulaire de recherche de biens
		 */
		$search = new PropertySearch;
		$form = $this->createForm(PropertySearchType::class, $search);
		$form->handleRequest($request);

		/**
		 * Création de la pagination et l'affichacge des biens par page
		 */
		// $properties = $repository->findAllVisible();
		$properties = $paginator->paginate(
			$repository->findAllVisibleQuery($search),
			$request->query->getInt('page', 1),
			12
		);
		dump($properties);

		return $this->render('agency/properties.html.twig', [
			'current_page' => 'properties',
			// 'current_page' => 'show_properties',
			'properties' => $properties,
			// 'property' => $property,
			'form' => $form->createView(),
		]);
	}

	/**
	 * @Route("/biens/{id}-{slug}", name="agency_show", requirements={"slug": "[a-z0-9\-]*"})
	 */
	public function show(Property $property, string $slug, Request $request, ContactNotification $contactNotification): Response
	{
		/**
		 * IF pemettant la vérification du slug.
		 * Si on est sur l'objet Property et qu'on modifie le slug
		 * Ce dernier nous redirigera sur la même page avec le slug qui correspond à l'objet
		 */
		if ($property->getSlug() !== $slug) {
			return $this->redirectToRoute('agency_show', [
				'id' => $property->getId(),
				'slug' => $property->getSlug(),
			], 301);
		}

		/**
		 * Formulaire de contact d'agent immobilier avec envoi de mail
		 */
		$contact = new Contact;
		$contact->setProperty($property);
		$form = $this->createForm(ContactType::class, $contact);
		$form->handleRequest($request);

		if ($form->isSubmitted() && $form->isValid()) {
			/**
			 * Gestion de l'envoi d'email via les entités de Notification
			 */
			$contactNotification->notify($contact);
			
			$this->addFlash('success', 'Votre email a bien été envoyé');

			// return $this->redirectToRoute('agency_show', [
			// 	'id' => $property->getId(),
			// 	'slug' => $property->getSlug(),
			// ]);
		}

		return $this->render('agency/show.html.twig', [
			'current_page' => 'properties',
			// 'current_page' => 'show_properties',
			'property' => $property,
			'form' => $form->createView(),
		]);
	}
}

symfony/grafikart3/templates/agency/_property.html.twig
<div class="card mb-4">

	<a href="{{ path('agency_show', {slug: property.slug, id: property.id}) }}">
		{% if property.filename %}
 			<img
			src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('my_thumb') }}" class="card-img-top" style="width: 100%; height: auto;">
			{# <img src="{{ vich_uploader_asset(property, 'imageFile')|imagine_filter('my_thumb') }}" class="card-img-top" style="width: 100%; height: auto;"> #}
		{% else %}
			<img src="{{ '/images/default.jpg' | imagine_filter('my_thumb') }}" class="card-img-top" style="width: 100%; height: auto;">
		{% endif %}
	</a>

	<div class="card-body">

		<h5 class="card-title">
			<a href="{{ path('agency_show', {slug: property.slug, id: property.id}) }}">{{ property.title }}</a>
		</h5>

		{# <p class="card-text">{{ property.description|nl2br }}</p> #}
		<p class="card-text">{{ property.surface }}m2 -
			{{ property.city }}
			({{ property.zipcode }})</p>

		<div class="text-primary" style="font-size: 2rem; font-weight: bold;">
			{{ property.formattedPrice }}
			€</div>

	</div>
</div>

symfony/grafikart3/templates/agency/create.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<div class="container mt-4">
		<h1>Créer les biens</h1>
	</div>
{% endblock %}

symfony/grafikart3/templates/agency/home.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<div class="jumbotron text-center">
		<h1>Agence Lorem ipsum</h1>

		<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi quo aspernatur, ut enim iure quos ullam iusto dolorum non. Aspernatur adipisci corporis odit ipsa, consequuntur mollitia soluta harum consequatur necessitatibus.</p>
	</div>

	<div class="container">
		<h1>Les derniers biens</h1>

		<div class="row flex">
			{% for property in properties %}
				<div class="col-3">
					<div class="card">
						<div class="card-body">
							<h5 class="card-title">
								<a href="{{ path('agency_show', {id: property.id, slug: property.slug}) }}">{{ property.title }}</a>
							</h5>

							<p class="card-text">{{ property.city }}
								({{ property.zipcode }})</p>

							<div class="text-success" style="font-weight: bold; font-size: 2rem;">{{ property.getFormattedPrice }}
								€</div>
						</div>
					</div>
				</div>
			{% endfor %}
		</div>
	</div>
{% endblock %}

symfony/grafikart3/templates/agency/properties.html.twig
{% extends 'base.html.twig' %}

{% block body %}

	<div class="jumbotron">
		<div class="container">

			{{ form_start(form) }}

			<div class="form-row align-items-end">
				<div class="col">
					{{ form_row(form.minSurface) }}
				</div>

				<div class="col">
					{{ form_row(form.maxPrice) }}
				</div>

				<div class="col">
					{{ form_row(form.options) }}
				</div>

				<div class="form-group">
					<div class="col">
						<button class="btn btn-primary">Rechercher</button>
					</div>
				</div>
			</div>

			{{ form_end(form) }}

		</div>
	</div>

	<div class="container mt-4">

		<h1>Liste des biens</h1>

		<div class="row">
			{% for property in properties %}

				<div class="col-md-4">
					{% include 'agency/_property.html.twig' %}
				</div>

			{% endfor %}
		</div>

		{# display navigation #}
		<div class="navigation">
			{{ knp_pagination_render(properties) }}
		</div>

	</div>

{% endblock %}

symfony/grafikart3/templates/agency/show.html.twig
{% extends 'base.html.twig' %}

{% block title property.title %}

{% block body %}
	<div class="jumbotron">
		<div class="container">

			{% for message in app.flashes('success') %}
				<div class="alert alert-success">
					{{ message }}
				</div>
			{% endfor %}

			{# Si le formulaire de contact n'est pas valide, renvoi d'un message alert danger #}
			{% if not form.vars.valid %}
				<div class="alert alert-danger">
					ERREUR. L'email de contact n'a pas été envoyé, veuillez modifier le formulaire de contact.
				</div>
			{% endif %}

			<div class="row">

				<div class="col-md-8">
					{% if property.filename %}
						<img
						src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('medium') }}" class="card-img-top" style="width: 100%; height: auto;">
						{# <img src="{{ vich_uploader_asset(property, 'imageFile')|imagine_filter('medium') }}" class="card-img-top" style="width: 100%; height: auto;"> #}
					{% else %}
						<img src="{{ '/images/default.jpg' | imagine_filter('medium') }}" class="card-img-top" style="width: 100%; height: auto;">
					{% endif %}
				</div>

				<div class="col-md-4">
					<h1>{{ property.title }}</h1>
					<h2>{{ property.rooms }}
						pièces -
						{{ property.surface }}
						m2</h2>
					<div class="text-primary" style="font-size: 4rem; font-weight: bold;">{{ property.formattedPrice }}
						€</div>

					<a href="#" class="btn btn-primary">Contacter l'agence</a>

					<div id="contactForm" class="mt-4">
						{{ form_start(form) }}
						<div class="row">
							<div class="col">{{ form_row(form.firstname) }}</div>
							<div class="col">{{ form_row(form.lastname) }}</div>
						</div>

						<div class="row">
							<div class="col">{{ form_row(form.phone) }}</div>
							<div class="col">{{ form_row(form.email) }}</div>
						</div>

						{{ form_rest(form) }}

						<div class="form-group">
							<button class="btn btn-primary">Envoyer</button>
						</div>
						{{ form_end(form) }}
					</div>

				</div>

			</div>

		</div>
	</div>

	<div class="container">

		<nav class="nav nav-tabs mb-4">
			{{ property.description|nl2br }}</nav>


		<div class="row">
			<div class="col-md-8">
				<h2>Caractéristiques</h2>
				<table class="table table-striped">
					<tr>
						<td>Surface habitable</td>
						<td>{{ property.surface }}
							m2</td>
					</tr>
					<tr>
						<td>Pièces</td>
						<td>{{ property.rooms }}</td>
					</tr>
					<tr>
						<td>Chambres</td>
						<td>{{ property.bedrooms }}</td>
					</tr>
					<tr>
						<td>Etage</td>
						<td>{{ property.floor }}</td>
					</tr>
					<tr>
						<td>Chauffage</td>
						<td>{{ property.heatType }}</td>
					</tr>
				</table>
			</div>

			<div class="col-md-4">
				<h2>Spécificités</h2>

				<ul class="list-group">
					{% for option in property.options %}
						<li class="list-group-item">
							{{ option.name }}
						</li>
					{% endfor %}
				</ul>
			</div>
		</div>
	</div>
{% endblock %}